# src/main/resources/application.yml
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: taskdb_anurag

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.anurag.taskapp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

info:
  app:
    name: Task Management API
    developer: Anurag
    version: 1.0.0